### ISSUE TITLE
Empty window

### ISSUE THREAD

**Issue by daudix-UFO** [nahuelwexd/Replay#123] opened 2022-07-08 21:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After install and launching app there is an empty window and nothing more

Nothing shows in terminal

### To Reproduce

1. Download latest flatpak
2. Install it via terminal `flatpak install app.drey.Replay.Devel.flatpak` in package directory
3. Launch app

### Expected behavior

A working app

### Screenshots

![Снимок экрана от 2022-07-09 00-35-16](https://user-images.githubusercontent.com/77155297/178073466-98e70084-8f5f-4f25-9540-e63f18b5c22b.png)

https://user-images.githubusercontent.com/77155297/178073487-6048fd98-cf26-4d5c-af97-5012dbb2e945.mp4

### OS

Fedora Linux 36 (Silverblue edition)

### Installation method

Flatpak from GitHub Actions

**Comment by nahuelwexd** [comment] 2022-07-08 21:43
@daudix-UFO Yes, this is the current state of the app, since relatively recently I decided to empty the UI to focus on reworking the core, and be able to provide a new design.

It is for this reason that it is not in Flathub or Flathub beta, and it is marked with "WIP" in the README title itself.

**Comment by nahuelwexd** [comment] 2022-07-08 21:44
Since this is not a bug, I will close it. If you want to follow the progress of the app, or collaborate, you can join the Telegram group linked in the README. Thanks :)

**Closed by nahuelwexd** 2022-07-08 21:44 UTC
Labels: bug
